### ISSUE TITLE
Addition: keychain parser

### ISSUE THREAD

**Issue by randomaccess3** [pstirparo/mac4n6#1]
I've written a small perl script that parses the output of the security command on OSX.
I've only tested it on a couple of keychains that I have available but it seems to provide a slightly more readable version that Apple does.

It can be found here; https://github.com/randomaccess3/MacForensics

**Comment by pstirparo** [comment]
Hi Phill,
with "slight" delay (really sorry for the long on-hold period of the project):  maybe I have missed it, but is there any new artifact location you wanted to add from this? Or simply to notify/add the tool to the project page?
If the latter, I think a better location could be to include it in https://github.com/meirwah/awesome-incident-response#osx-evidence-collection

**Comment by randomaccess3** [comment]
I only vaguely remember what I used this script for - probably doesn't even work on todays systems
